import express, {
  Request,
  Response,
  NextFunction,
  RequestHandler,
} from "express";
import { z } from "zod";
import { getLogger } from "../lib/logger-factory";

const logger = getLogger("integrations", "github-bug-report");
import { requirePermission, getAuthenticatedUser } from "../middleware/auth";
import { githubService } from "../services/github-service";
import { BugReportRequest, BugReportResponse, Permission } from "@mini-infra/types";

const router = express.Router();

// Request validation schemas
const bugReportSystemInfoSchema = z.object({
  userAgent: z.string(),
  screenWidth: z.number(),
  screenHeight: z.number(),
  currentRoute: z.string(),
  timestamp: z.string(),
  appVersion: z.string().optional(),
  platform: z.string().optional(),
});

const bugReportUserDataSchema = z.object({
  title: z.string().min(1, "Title is required").max(256, "Title is too long"),
  description: z
    .string()
    .min(10, "Description must be at least 10 characters")
    .max(5000, "Description is too long"),
  stepsToReproduce: z.string().max(2000).optional(),
  expectedBehavior: z.string().max(1000).optional(),
  actualBehavior: z.string().max(1000).optional(),
});

const bugReportRequestSchema = z.object({
  userData: bugReportUserDataSchema,
  systemInfo: bugReportSystemInfoSchema,
});

/**
 * Format a bug report into a GitHub issue body
 * @param userData User-provided bug report data
 * @param systemInfo Auto-collected system information
 * @returns Formatted markdown issue body
 */
function formatBugReportBody(
  userData: BugReportRequest["userData"],
  systemInfo: BugReportRequest["systemInfo"],
): string {
  let body = "## Bug Description\n\n";
  body += `${userData.description}\n\n`;

  if (userData.stepsToReproduce) {
    body += "## Steps to Reproduce\n\n";
    body += `${userData.stepsToReproduce}\n\n`;
  }

  if (userData.expectedBehavior) {
    body += "## Expected Behavior\n\n";
    body += `${userData.expectedBehavior}\n\n`;
  }

  if (userData.actualBehavior) {
    body += "## Actual Behavior\n\n";
    body += `${userData.actualBehavior}\n\n`;
  }

  body += "## System Information\n\n";
  body += "| Property | Value |\n";
  body += "| --- | --- |\n";
  body += `| **Browser** | ${systemInfo.userAgent} |\n`;
  body += `| **Screen Resolution** | ${systemInfo.screenWidth}x${systemInfo.screenHeight} |\n`;
  body += `| **Current Route** | \`${systemInfo.currentRoute}\` |\n`;
  body += `| **Timestamp** | ${systemInfo.timestamp} |\n`;

  if (systemInfo.appVersion) {
    body += `| **App Version** | ${systemInfo.appVersion} |\n`;
  }

  if (systemInfo.platform) {
    body += `| **Platform** | ${systemInfo.platform} |\n`;
  }

  body += "\n---\n\n";
  body += "*This bug report was auto-generated by the Mini Infra bug reporting system.*\n";

  return body;
}

/**
 * POST /api/github/bug-report - Create a bug report as a GitHub issue
 */
router.post("/", requirePermission(Permission.SettingsWrite) as RequestHandler, (async (
  req: Request,
  res: Response,
  next: NextFunction,
) => {
  const requestId = req.headers["x-request-id"] as string;
  const user = getAuthenticatedUser(req);
  const userId = user?.id || "system";

  logger.debug(
    {
      requestId,
      userId,
      hasUserData: !!req.body.userData,
      hasSystemInfo: !!req.body.systemInfo,
    },
    "Bug report submission requested",
  );

  try {
    // Validate request body
    const validationResult = bugReportRequestSchema.safeParse(req.body);
    if (!validationResult.success) {
      logger.warn(
        {
          requestId,
          userId,
          errors: validationResult.error.flatten(),
        },
        "Invalid bug report request",
      );

      return res.status(400).json({
        success: false,
        error: "Invalid request parameters",
        details: validationResult.error.flatten(),
      });
    }

    const { userData, systemInfo } = validationResult.data;

    // Format the issue body
    const issueBody = formatBugReportBody(userData, systemInfo);

    logger.debug(
      {
        requestId,
        userId,
        title: userData.title,
        bodyLength: issueBody.length,
      },
      "Creating GitHub issue for bug report",
    );

    // Create the GitHub issue
    const issue = await githubService.createIssue({
      title: userData.title,
      body: issueBody,
      labels: ["bug", "user-reported"],
    });

    logger.info(
      {
        requestId,
        userId,
        issueNumber: issue.number,
        issueUrl: issue.html_url,
      },
      "Bug report created successfully",
    );

    const response: BugReportResponse = {
      success: true,
      data: {
        issueNumber: issue.number,
        issueUrl: issue.html_url,
        title: issue.title,
      },
      message: "Bug report created successfully",
    };

    res.status(201).json(response);
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";

    logger.error(
      {
        requestId,
        userId,
        error: errorMessage,
      },
      "Failed to create bug report",
    );

    // githubService.createIssue() already maps every known failure mode
    // (not configured -> ValidationError, timeout/rate-limit/auth ->
    // ServiceError via toServiceError/GITHUB_MAPPINGS) onto a typed error
    // with the correct status code — let the central middleware render it
    // instead of re-deriving the status from string-matching the message.
    next(error);
  }
}) as RequestHandler);

export default router;
