// ====================
// Error Codes
// ====================
//
// Machine-readable error codes shared between client and server. No runtime
// deps (per the lib zero-external-dependency invariant — see lib/CLAUDE.md).
//
// Naming rule: SCREAMING_SNAKE, shaped `<DOMAIN>_<REASON>`. Seeded here with
// only what the current phase of the error-handling overhaul needs
// (docs/planning/not-shipped/error-handling-overhaul-plan.md, §4.1); each
// later phase adds its own domain's codes as it migrates.
export const ErrorCode = {
  // Postgres backup domain (Phase 1 reference migration)
  POSTGRES_DB_CONFIG_EXISTS: "POSTGRES_DB_CONFIG_EXISTS",
  POSTGRES_BACKUP_CONFIG_EXISTS: "POSTGRES_BACKUP_CONFIG_EXISTS",

  // NATS
  // — identity re-key guard (nats-identity-errors.ts / NatsControlPlaneService)
  NATS_IDENTITY_SEED_MISSING: "NATS_IDENTITY_SEED_MISSING",
  NATS_IDENTITY_SEED_MISMATCH: "NATS_IDENTITY_SEED_MISMATCH",
  // — identity-seed backup/restore (nats-identity-seed-backup.ts, self-backup-seed-restore.ts)
  NATS_SELF_BACKUP_NOT_FOUND: "NATS_SELF_BACKUP_NOT_FOUND",
  NATS_SELF_BACKUP_NO_SEED_ENTRY: "NATS_SELF_BACKUP_NO_SEED_ENTRY",
  NATS_SEED_BACKUP_DECRYPT_FAILED: "NATS_SEED_BACKUP_DECRYPT_FAILED",
  NATS_IDENTITY_SEED_RESTORE_CONFLICT: "NATS_IDENTITY_SEED_RESTORE_CONFLICT",
  // — account/credential/stream/consumer CRUD (nats-control-plane-service.ts)
  NATS_ACCOUNT_EXISTS: "NATS_ACCOUNT_EXISTS",
  NATS_ACCOUNT_NOT_FOUND: "NATS_ACCOUNT_NOT_FOUND",
  NATS_SYSTEM_ACCOUNT_PROTECTED: "NATS_SYSTEM_ACCOUNT_PROTECTED",
  NATS_CREDENTIAL_PROFILE_EXISTS: "NATS_CREDENTIAL_PROFILE_EXISTS",
  NATS_CREDENTIAL_PROFILE_NOT_FOUND: "NATS_CREDENTIAL_PROFILE_NOT_FOUND",
  NATS_STREAM_EXISTS: "NATS_STREAM_EXISTS",
  NATS_STREAM_NOT_FOUND: "NATS_STREAM_NOT_FOUND",
  NATS_CONSUMER_EXISTS: "NATS_CONSUMER_EXISTS",
  NATS_CONSUMER_NOT_FOUND: "NATS_CONSUMER_NOT_FOUND",
  NATS_INVALID_NAME: "NATS_INVALID_NAME",
  NATS_INVALID_SUBJECT: "NATS_INVALID_SUBJECT",
  // — stack-apply NATS phase (stack-nats-apply-orchestrator.ts)
  NATS_NOT_CONFIGURED: "NATS_NOT_CONFIGURED",
  NATS_SUBJECT_PREFIX_NOT_ALLOWLISTED: "NATS_SUBJECT_PREFIX_NOT_ALLOWLISTED",
  NATS_IMPORT_INVALID: "NATS_IMPORT_INVALID",
  NATS_IMPORT_PRODUCER_NOT_FOUND: "NATS_IMPORT_PRODUCER_NOT_FOUND",
  NATS_IMPORT_PRODUCER_NOT_READY: "NATS_IMPORT_PRODUCER_NOT_READY",
  // — subject-prefix allowlist admin CRUD (nats-prefix-allowlist-service.ts)
  NATS_PREFIX_ALLOWLIST_INVALID: "NATS_PREFIX_ALLOWLIST_INVALID",
  NATS_PREFIX_ALLOWLIST_NOT_FOUND: "NATS_PREFIX_ALLOWLIST_NOT_FOUND",
  NATS_PREFIX_ALLOWLIST_OVERLAP: "NATS_PREFIX_ALLOWLIST_OVERLAP",

  // Environments / networks
  ENVIRONMENT_NAME_EXISTS: "ENVIRONMENT_NAME_EXISTS",
  ENVIRONMENT_NETWORK_TYPE_CONFLICT: "ENVIRONMENT_NETWORK_TYPE_CONFLICT",
  ENVIRONMENT_NOT_FOUND: "ENVIRONMENT_NOT_FOUND",
  ENVIRONMENT_HAPROXY_MIGRATION_IN_PROGRESS: "ENVIRONMENT_HAPROXY_MIGRATION_IN_PROGRESS",
  DOCKER_NETWORK_NOT_FOUND: "DOCKER_NETWORK_NOT_FOUND",
  DOCKER_NETWORK_IN_USE: "DOCKER_NETWORK_IN_USE",
  MANAGED_NETWORK_NOT_FOUND: "MANAGED_NETWORK_NOT_FOUND",
  // HAProxy (Phase 8 — frontend/backend/server/instance + data-plane)
  HAPROXY_FRONTEND_NOT_FOUND: "HAPROXY_FRONTEND_NOT_FOUND",
  HAPROXY_FRONTEND_TYPE_MISMATCH: "HAPROXY_FRONTEND_TYPE_MISMATCH",
  HAPROXY_HOSTNAME_IN_USE: "HAPROXY_HOSTNAME_IN_USE",
  HAPROXY_ROUTE_NOT_FOUND: "HAPROXY_ROUTE_NOT_FOUND",
  HAPROXY_ROUTE_FRONTEND_MISMATCH: "HAPROXY_ROUTE_FRONTEND_MISMATCH",
  HAPROXY_BACKEND_NOT_FOUND: "HAPROXY_BACKEND_NOT_FOUND",
  HAPROXY_SERVER_NOT_FOUND: "HAPROXY_SERVER_NOT_FOUND",
  HAPROXY_CERTIFICATE_NOT_FOUND: "HAPROXY_CERTIFICATE_NOT_FOUND",
  HAPROXY_CERTIFICATE_NOT_READY: "HAPROXY_CERTIFICATE_NOT_READY",
  HAPROXY_STORAGE_NOT_CONFIGURED: "HAPROXY_STORAGE_NOT_CONFIGURED",
  HAPROXY_ENVIRONMENT_NOT_FOUND: "HAPROXY_ENVIRONMENT_NOT_FOUND",
  HAPROXY_STACK_NOT_FOUND: "HAPROXY_STACK_NOT_FOUND",
  HAPROXY_CONTAINER_UNAVAILABLE: "HAPROXY_CONTAINER_UNAVAILABLE",
  HAPROXY_NETWORK_NOT_FOUND: "HAPROXY_NETWORK_NOT_FOUND",
  HAPROXY_CONTAINER_NOT_ELIGIBLE: "HAPROXY_CONTAINER_NOT_ELIGIBLE",
  HAPROXY_CONTAINER_VALIDATION_FAILED: "HAPROXY_CONTAINER_VALIDATION_FAILED",
  HAPROXY_SETUP_IN_PROGRESS: "HAPROXY_SETUP_IN_PROGRESS",
  HAPROXY_DATAPLANE_RESOURCE_NOT_FOUND: "HAPROXY_DATAPLANE_RESOURCE_NOT_FOUND",
  HAPROXY_DATAPLANE_VERSION_CONFLICT: "HAPROXY_DATAPLANE_VERSION_CONFLICT",
  // Certificates / TLS / ACME / DNS (Phase 5)
  TLS_CERTIFICATE_NOT_FOUND: "TLS_CERTIFICATE_NOT_FOUND",
  TLS_CERTIFICATE_ISSUANCE_IN_PROGRESS: "TLS_CERTIFICATE_ISSUANCE_IN_PROGRESS",
  TLS_RENEWAL_NOT_FOUND: "TLS_RENEWAL_NOT_FOUND",
  TLS_STORAGE_NOT_CONFIGURED: "TLS_STORAGE_NOT_CONFIGURED",
  TLS_ACME_EMAIL_NOT_CONFIGURED: "TLS_ACME_EMAIL_NOT_CONFIGURED",
  TLS_INVALID_RENEWAL_CRON: "TLS_INVALID_RENEWAL_CRON",
  DNS_ZONE_NOT_FOUND: "DNS_ZONE_NOT_FOUND",
  DNS_INVALID_CACHE_CRON: "DNS_INVALID_CACHE_CRON",
  CLOUDFLARE_ZONE_NOT_FOUND: "CLOUDFLARE_ZONE_NOT_FOUND",
  CLOUDFLARE_API_TOKEN_INVALID: "CLOUDFLARE_API_TOKEN_INVALID",
  CLOUDFLARE_ACCOUNT_ID_INVALID: "CLOUDFLARE_ACCOUNT_ID_INVALID",
  CLOUDFLARE_API_TOKEN_NOT_CONFIGURED: "CLOUDFLARE_API_TOKEN_NOT_CONFIGURED",
  CLOUDFLARE_ACCOUNT_ID_NOT_CONFIGURED: "CLOUDFLARE_ACCOUNT_ID_NOT_CONFIGURED",
  CLOUDFLARE_CONNECTIVITY_STATUS_NOT_FOUND: "CLOUDFLARE_CONNECTIVITY_STATUS_NOT_FOUND",
  CLOUDFLARE_TUNNEL_NOT_FOUND: "CLOUDFLARE_TUNNEL_NOT_FOUND",
  CLOUDFLARE_TUNNEL_CONFIG_UNAVAILABLE: "CLOUDFLARE_TUNNEL_CONFIG_UNAVAILABLE",
  CLOUDFLARE_TUNNEL_HOSTNAME_EXISTS: "CLOUDFLARE_TUNNEL_HOSTNAME_EXISTS",
  CLOUDFLARE_TUNNEL_HOSTNAME_NOT_FOUND: "CLOUDFLARE_TUNNEL_HOSTNAME_NOT_FOUND",
  CLOUDFLARE_MANAGED_TUNNEL_EXISTS: "CLOUDFLARE_MANAGED_TUNNEL_EXISTS",
  CLOUDFLARE_MANAGED_TUNNEL_NOT_FOUND: "CLOUDFLARE_MANAGED_TUNNEL_NOT_FOUND",
  CLOUDFLARE_MANAGED_TUNNEL_STACK_RUNNING: "CLOUDFLARE_MANAGED_TUNNEL_STACK_RUNNING",
  CLOUDFLARE_MANAGED_TUNNEL_REQUIRES_INTERNET_ENV: "CLOUDFLARE_MANAGED_TUNNEL_REQUIRES_INTERNET_ENV",
  CLOUDFLARE_TUNNEL_ENVIRONMENT_NOT_FOUND: "CLOUDFLARE_TUNNEL_ENVIRONMENT_NOT_FOUND",
  CLOUDFLARE_TUNNEL_TOKEN_ENVIRONMENT_REQUIRED: "CLOUDFLARE_TUNNEL_TOKEN_ENVIRONMENT_REQUIRED",
  // Containers / images / volumes (Phase 7)
  CONTAINER_NOT_FOUND: "CONTAINER_NOT_FOUND",
  CONTAINER_ALREADY_IN_STATE: "CONTAINER_ALREADY_IN_STATE",
  CONTAINER_NOT_RUNNING: "CONTAINER_NOT_RUNNING",
  DOCKER_NOT_CONNECTED: "DOCKER_NOT_CONNECTED",
  IMAGE_NOT_FOUND: "IMAGE_NOT_FOUND",
  IMAGE_AUTH_FAILED: "IMAGE_AUTH_FAILED",
  VOLUME_NOT_FOUND: "VOLUME_NOT_FOUND",
  VOLUME_IN_USE: "VOLUME_IN_USE",
  VOLUME_FILE_NOT_FOUND: "VOLUME_FILE_NOT_FOUND",

  // Generic, cross-domain fallbacks emitted by the central error middleware
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL: "INTERNAL",

  // Auth / API keys / users / permissions (Phase 9)
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
  PERMISSION_PRESET_NOT_FOUND: "PERMISSION_PRESET_NOT_FOUND",
  PERMISSION_PRESET_NAME_EXISTS: "PERMISSION_PRESET_NAME_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_EMAIL_EXISTS: "USER_EMAIL_EXISTS",
  USER_SELF_DELETE_FORBIDDEN: "USER_SELF_DELETE_FORBIDDEN",
  AUTH_SETUP_ALREADY_COMPLETE: "AUTH_SETUP_ALREADY_COMPLETE",
  AUTH_SETUP_NOT_IN_PROGRESS: "AUTH_SETUP_NOT_IN_PROGRESS",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_EMAIL_NOT_ALLOWED: "AUTH_EMAIL_NOT_ALLOWED",
  AUTH_PASSWORD_TOO_WEAK: "AUTH_PASSWORD_TOO_WEAK",
  AUTH_RECOVERY_TOKEN_INVALID: "AUTH_RECOVERY_TOKEN_INVALID",
  AUTH_CURRENT_PASSWORD_REQUIRED: "AUTH_CURRENT_PASSWORD_REQUIRED",
  AUTH_CURRENT_PASSWORD_INCORRECT: "AUTH_CURRENT_PASSWORD_INCORRECT",
  AUTH_NO_PASSWORD_SET: "AUTH_NO_PASSWORD_SET",
  AUTH_NOT_AUTHENTICATED: "AUTH_NOT_AUTHENTICATED",
  AUTH_GOOGLE_OAUTH_CREDENTIALS_REQUIRED: "AUTH_GOOGLE_OAUTH_CREDENTIALS_REQUIRED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
