// ====================
// Error Codes
// ====================
//
// Machine-readable error codes shared between client and server. No runtime
// deps (per the lib zero-external-dependency invariant — see lib/CLAUDE.md).
//
// Naming rule: SCREAMING_SNAKE, shaped `<DOMAIN>_<REASON>`. Seeded here with
// only what the current phase of the error-handling overhaul needs
// (docs/planning/not-shipped/error-handling-overhaul-plan.md, §4.1); each
// later phase adds its own domain's codes as it migrates.
export const ErrorCode = {
  // Postgres backup domain (Phase 1 reference migration)
  POSTGRES_DB_CONFIG_EXISTS: "POSTGRES_DB_CONFIG_EXISTS",
  POSTGRES_BACKUP_CONFIG_EXISTS: "POSTGRES_BACKUP_CONFIG_EXISTS",

  // Generic, cross-domain fallbacks emitted by the central error middleware
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL: "INTERNAL",
  // Generic auth precondition, reused by multiple Phase 10 routes (egress
  // fw-agent config, self-update trigger) that defensively check for a
  // resolved user id after `requirePermission` already ran.
  USER_NOT_AUTHENTICATED: "USER_NOT_AUTHENTICATED",

  // Vault / secrets / egress / self-update / monitoring (Phase 10)
  // ── Vault: passphrase / bootstrap / seal state ──
  VAULT_NOT_CONFIGURED: "VAULT_NOT_CONFIGURED",
  VAULT_ALREADY_BOOTSTRAPPED: "VAULT_ALREADY_BOOTSTRAPPED",
  VAULT_LOCKED: "VAULT_LOCKED",
  VAULT_UNSEAL_FAILED: "VAULT_UNSEAL_FAILED",
  VAULT_STATE_INCOMPLETE: "VAULT_STATE_INCOMPLETE",
  VAULT_INVALID_PASSPHRASE: "VAULT_INVALID_PASSPHRASE",
  VAULT_UNLOCK_RATE_LIMITED: "VAULT_UNLOCK_RATE_LIMITED",
  VAULT_PASSPHRASE_ALREADY_SET: "VAULT_PASSPHRASE_ALREADY_SET",
  // ── Vault: policies / AppRoles ──
  VAULT_POLICY_NOT_FOUND: "VAULT_POLICY_NOT_FOUND",
  VAULT_POLICY_DRAFT_EMPTY: "VAULT_POLICY_DRAFT_EMPTY",
  VAULT_POLICY_INVALID_NAME: "VAULT_POLICY_INVALID_NAME",
  VAULT_POLICY_IN_USE: "VAULT_POLICY_IN_USE",
  VAULT_SYSTEM_POLICY_IMMUTABLE: "VAULT_SYSTEM_POLICY_IMMUTABLE",
  VAULT_APPROLE_NOT_FOUND: "VAULT_APPROLE_NOT_FOUND",
  VAULT_APPROLE_BOUND_TO_STACKS: "VAULT_APPROLE_BOUND_TO_STACKS",
  VAULT_APPROLE_INVALID_NAME: "VAULT_APPROLE_INVALID_NAME",
  VAULT_APPROLE_BINDING_MISSING: "VAULT_APPROLE_BINDING_MISSING",
  VAULT_UNREACHABLE_FOR_APPLY: "VAULT_UNREACHABLE_FOR_APPLY",
  VAULT_HTTP_ERROR: "VAULT_HTTP_ERROR",
  // ── Vault: brokered KV API ──
  VAULT_KV_INVALID_PATH: "VAULT_KV_INVALID_PATH",
  VAULT_KV_INVALID_FIELD: "VAULT_KV_INVALID_FIELD",
  VAULT_KV_INVALID_DATA: "VAULT_KV_INVALID_DATA",
  VAULT_KV_PATH_NOT_FOUND: "VAULT_KV_PATH_NOT_FOUND",
  VAULT_KV_FIELD_NOT_FOUND: "VAULT_KV_FIELD_NOT_FOUND",
  VAULT_KV_PERMISSION_DENIED: "VAULT_KV_PERMISSION_DENIED",
  VAULT_KV_RATE_LIMITED: "VAULT_KV_RATE_LIMITED",
  VAULT_KV_SEALED: "VAULT_KV_SEALED",
  VAULT_KV_STANDBY: "VAULT_KV_STANDBY",
  VAULT_KV_UNAVAILABLE: "VAULT_KV_UNAVAILABLE",
  VAULT_KV_ERROR: "VAULT_KV_ERROR",
  VAULT_KV_DESTROY_FORBIDDEN: "VAULT_KV_DESTROY_FORBIDDEN",

  // ── Egress ──
  EGRESS_POLICY_NOT_FOUND: "EGRESS_POLICY_NOT_FOUND",
  EGRESS_POLICY_ARCHIVED: "EGRESS_POLICY_ARCHIVED",
  EGRESS_RULE_NOT_FOUND: "EGRESS_RULE_NOT_FOUND",
  EGRESS_FW_AGENT_STARTUP_IN_PROGRESS: "EGRESS_FW_AGENT_STARTUP_IN_PROGRESS",
  EGRESS_GATEWAY_ERROR: "EGRESS_GATEWAY_ERROR",

  // ── Storage / secrets backends ──
  STORAGE_NOT_CONFIGURED: "STORAGE_NOT_CONFIGURED",
  STORAGE_PROVIDER_UNREGISTERED: "STORAGE_PROVIDER_UNREGISTERED",
  PROVIDER_NO_LONGER_CONFIGURED: "PROVIDER_NO_LONGER_CONFIGURED",
  STORAGE_AZURE_CONNECTION_STRING_EMPTY: "STORAGE_AZURE_CONNECTION_STRING_EMPTY",
  STORAGE_AZURE_CONNECTION_STRING_INVALID: "STORAGE_AZURE_CONNECTION_STRING_INVALID",
  STORAGE_GOOGLE_DRIVE_OAUTH_NOT_CONFIGURED: "STORAGE_GOOGLE_DRIVE_OAUTH_NOT_CONFIGURED",
  STORAGE_GOOGLE_DRIVE_FILE_NOT_FOUND: "STORAGE_GOOGLE_DRIVE_FILE_NOT_FOUND",
  STORAGE_GOOGLE_DRIVE_AUTH_FAILED: "STORAGE_GOOGLE_DRIVE_AUTH_FAILED",
  CLIENT_CREDENTIALS_MISSING: "CLIENT_CREDENTIALS_MISSING",
  PUBLIC_URL_NOT_CONFIGURED: "PUBLIC_URL_NOT_CONFIGURED",
  STORAGE_CONNECTIVITY_NOT_FOUND: "STORAGE_CONNECTIVITY_NOT_FOUND",
  STORAGE_PROVIDER_ACTIVE_CANNOT_DISCONNECT: "STORAGE_PROVIDER_ACTIVE_CANNOT_DISCONNECT",
  PROVIDER_HAS_REFERENCING_ROWS: "PROVIDER_HAS_REFERENCING_ROWS",

  // ── Backup execution ──
  BACKUP_STACK_NOT_DEPLOYED: "BACKUP_STACK_NOT_DEPLOYED",
  BACKUP_CONCURRENCY_CAP_REACHED: "BACKUP_CONCURRENCY_CAP_REACHED",
  BACKUP_DATABASE_NOT_FOUND: "BACKUP_DATABASE_NOT_FOUND",

  // ── Self-update ──
  SELF_UPDATE_IN_PROGRESS: "SELF_UPDATE_IN_PROGRESS",
  SELF_UPDATE_IMAGE_NOT_ALLOWED: "SELF_UPDATE_IMAGE_NOT_ALLOWED",
  SELF_UPDATE_CONTAINER_ID_UNKNOWN: "SELF_UPDATE_CONTAINER_ID_UNKNOWN",
  SELF_UPDATE_IMAGE_PULL_FAILED: "SELF_UPDATE_IMAGE_PULL_FAILED",

  // ── Monitoring ──
  MONITORING_STACK_NOT_FOUND: "MONITORING_STACK_NOT_FOUND",
  MONITORING_SERVICE_UNAVAILABLE: "MONITORING_SERVICE_UNAVAILABLE",
  MONITORING_QUERY_PARAM_MISSING: "MONITORING_QUERY_PARAM_MISSING",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
