// ====================
// Error Codes
// ====================
//
// Machine-readable error codes shared between client and server. No runtime
// deps (per the lib zero-external-dependency invariant — see lib/CLAUDE.md).
//
// Naming rule: SCREAMING_SNAKE, shaped `<DOMAIN>_<REASON>`. Seeded here with
// only what the current phase of the error-handling overhaul needs
// (docs/planning/not-shipped/error-handling-overhaul-plan.md, §4.1); each
// later phase adds its own domain's codes as it migrates.
export const ErrorCode = {
  // Postgres backup domain (Phase 1 reference migration)
  POSTGRES_DB_CONFIG_EXISTS: "POSTGRES_DB_CONFIG_EXISTS",
  POSTGRES_BACKUP_CONFIG_EXISTS: "POSTGRES_BACKUP_CONFIG_EXISTS",

  // HAProxy (Phase 8 — frontend/backend/server/instance + data-plane)
  HAPROXY_FRONTEND_NOT_FOUND: "HAPROXY_FRONTEND_NOT_FOUND",
  HAPROXY_FRONTEND_TYPE_MISMATCH: "HAPROXY_FRONTEND_TYPE_MISMATCH",
  HAPROXY_HOSTNAME_IN_USE: "HAPROXY_HOSTNAME_IN_USE",
  HAPROXY_ROUTE_NOT_FOUND: "HAPROXY_ROUTE_NOT_FOUND",
  HAPROXY_ROUTE_FRONTEND_MISMATCH: "HAPROXY_ROUTE_FRONTEND_MISMATCH",
  HAPROXY_BACKEND_NOT_FOUND: "HAPROXY_BACKEND_NOT_FOUND",
  HAPROXY_SERVER_NOT_FOUND: "HAPROXY_SERVER_NOT_FOUND",
  HAPROXY_CERTIFICATE_NOT_FOUND: "HAPROXY_CERTIFICATE_NOT_FOUND",
  HAPROXY_CERTIFICATE_NOT_READY: "HAPROXY_CERTIFICATE_NOT_READY",
  HAPROXY_STORAGE_NOT_CONFIGURED: "HAPROXY_STORAGE_NOT_CONFIGURED",
  HAPROXY_ENVIRONMENT_NOT_FOUND: "HAPROXY_ENVIRONMENT_NOT_FOUND",
  HAPROXY_STACK_NOT_FOUND: "HAPROXY_STACK_NOT_FOUND",
  HAPROXY_CONTAINER_UNAVAILABLE: "HAPROXY_CONTAINER_UNAVAILABLE",
  HAPROXY_NETWORK_NOT_FOUND: "HAPROXY_NETWORK_NOT_FOUND",
  HAPROXY_CONTAINER_NOT_ELIGIBLE: "HAPROXY_CONTAINER_NOT_ELIGIBLE",
  HAPROXY_CONTAINER_VALIDATION_FAILED: "HAPROXY_CONTAINER_VALIDATION_FAILED",
  HAPROXY_SETUP_IN_PROGRESS: "HAPROXY_SETUP_IN_PROGRESS",
  HAPROXY_DATAPLANE_RESOURCE_NOT_FOUND: "HAPROXY_DATAPLANE_RESOURCE_NOT_FOUND",
  HAPROXY_DATAPLANE_VERSION_CONFLICT: "HAPROXY_DATAPLANE_VERSION_CONFLICT",

  // Generic, cross-domain fallbacks emitted by the central error middleware
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
